### ISSUE TITLE
Can we change what enchanted books players can get?

### ISSUE THREAD

**Issue by Aww5hucks** [AdvancedWipe/Minecraft_FreeRPG_1.16#7]
Hello,

Is there a way to specify which enchanted books players can get from things like woodcutting and fishing?

**Comment by AdvancedWipe** [comment]
Yes, you can. Change the values in the `perkConfig.yml`. Look for `woodcutting` and `fishing`. Everything you get by default is configured in this file. Change it, save it  and restart your server
